server:
  port: 9040

spring:
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672
  cloud:
    stream:
      bindings:
        input:
          destination: tasktopic

logging:
  level:
    org.springframework.cloud.task: debug
    org.springframework.cloud.stream: debug









