server:
  port: 9030

logging:
  level:
    org.springframework.cloud.task : debug
spring:
  datasource:
    name: postgresql
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/task_db
    username: postgres
    password: postgres

  jpa:
    database: postgresql
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties.hibernate.temp.use_jdbc_metadata_defaults: false